---
title: "Case Study 01"
author: "Alexy Morris"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#With the Beer and Breweries dataset provided by you, the CEO and CFO of Budweiser, our team was able to answer the questions you presented and have even addressesed some additional questions that arose. As a disclaimer we are working on a relatively local scale so all information should only be eneralized the the United States of America, our team would not recommend utalizing the same infomation obroad. Overall our team firmly believes that the following work will reflect the current and future trends in the craft beer market. 
```
#1-How many breweries are present in each state?

map <- Breweries %>% count(State)
map

map$State <- state.name[match(map$State,state.abb)]
map 

names(map)[names(map) == "State"] <- "state"

library(usmap)
library(ggplot2)

plot_usmap(data = map, values = "n", color = "red") + 
  scale_fill_continuous(name = "Brewery Number", label = scales::comma) + 
  theme(legend.position = "right")

#In this section, we automated the counting process using the 51 states as catcategories and then counted the number of times said category appears in our data.

#Through the 50 states we see that the highest number of breweries is in ___ with ____ and the lowest is in ___ with ____. That said most states are in the middle with between __ and __.
```
#2-Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file. 

library(dplyr)

x <- data.frame(Beers)
y <- data.frame(Breweries)
names(x)[names(x) == "Brewery_id"] <- "Brew_ID"
names(x)[names(x) == "Name"] <- "Beer_Name"

Case <- merge(x, y, by="Brew_ID", all = TRUE)
View(Case)

head(Case, n=6)

tail(Case, n=6)

#For convienience we combined the 2 dataframes given by matching up the brewery id numbers. We also took the time to rename a few columns for easy identification


```

#3-Address the missing values in each column

colSums(is.na(Case))

#While giving the data a cursurary glance our team noticed a number of missing values specifically in the IBU and ABV columns; unfortounely upon closer examination we see there are 1000+ missing values across our columns. The volume of missing vales means that it would be incredibly labour intensive on our teams part to fill the blanks manuelly. 

```

#4-Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.

alcohol = Case %>% select(Name, ABV, State) %>% filter(!is.na(ABV))
bitterness = Case %>% select(Name, IBU, State) %>% filter(!is.na(IBU))

MM_Alc <- alcohol %>% group_by(State) %>% summarise(Max=max(ABV), Min=min(ABV), Median=median(ABV))

MM_Alc_tophalf <- head(MM_Alc, n=25)
MM_Alc_bothalf <- tail(MM_Alc, n=26)

barplot(height=MM_Alc_tophalf$Median, names=MM_Alc_tophalf$State, col="#69b3a2", horiz=T, las=1)
barplot(height=MM_Alc_bothalf$Median, names=MM_Alc_bothalf$State, col="#69b3a2", horiz=T, las=1)
  
MM_bit <- bitterness %>% group_by(State) %>% summarise(Ma=max(IBU), Mi=min(IBU), Med=median(IBU))

MM_bit_tophalf <- head(MM_bit, n=25)
MM_bit_bothalf <- tail(MM_bit, n=26)

barplot(height=MM_bit$Med, names=MM_bit$State, col="#69b3d2",horiz=T, las=1)

barplot(height=MM_bit_tophalf$Med, names=MM_bit_tophalf$State, col="#69b3d2", horiz=T, las=1)
barplot(height=MM_bit_bothalf$Med, names=MM_bit_bothalf$State, col="#69b3d2", horiz=T, las=1)
  
#To compute the median ABV and IBU level for each state we first broke down the larger given dataframe to only the needed variables in order to save on computation times. Then we got to the relevant calculations and lastly broke the medians into two dataframes  
```
#5-Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?

M_ABV = Case %>% slice_max(ABV, n = 5)
M_ABV

M_IBU = Case %>% slice_max(IBU, n = 5)
M_IBU

#For the fifth question we simply reorginized the graphs from greatest ABV to least ABV and again from greatest to least IBU
```
#6-Comment on the summary statistics and distribution of the ABV variable.
summary(Case$ABV)
hist(Case$ABV, main="ABV Distribution", xlab="ABV", col="red")

```
#7- Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.

ggplot(data = Case, mapping = aes(x = ABV, y = IBU))+ geom_point() + geom_smooth(method = lm) 

lm(ABV ~ IBU, data=Case)

#To address the relationship between ABV and IBU we have graphed IBU with respecet to ABV and created a linear model to highlight the direct relationship between the two
```
#8-Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs...

library(tidyverse)
library(class)
library(caret)

Case$TIPA <- grepl("IPA", Case$Style, ignore.case = T)
Case$TAle <- grepl("Ale", Case$Style, ignore.case = T)

Base_IPA = Case %>% select(ABV, IBU, TIPA) %>% filter(!is.na(ABV)) %>% filter(!is.na(IBU))

test = data.frame(ABV = .05, IBU = 75)
 
knn(Base_IPA[,c(1,2)], test, Base_IPA$TIPA, k = 5, prob = TRUE)
knn(Base_IPA[,c(1,2)], test, Base_IPA$TIPA, k = 15, prob = TRUE)

#For our KNN classification we have taken the essentially the same scatter plot from above and plotted different test points to examine the likely of a beer with our same ABV and IBU being a IPA or an Ale
```
